export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/ac-home/index',
    'pages/approval-workbench/index',
    'pages/approval-detail/index',
    'pages/abnormal-counter/index',
    'pages/data-report/index',
    'pages/ac-profile/index',
    'pages/ba-home/index',
    'pages/ba-daily/index',
    'pages/ba-daily-history/index',
    'pages/ba-monthly/index',
    'pages/ba-monthly-history/index',
    'pages/ba-todo-list/index',
    'pages/ba-profile/index',
    'pages/ba-abnormal-data/index',
    'pages/ba-competitor-mgmt/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: 'CSP竞品情报系统',
    navigationBarTextStyle: 'black',
  },
})
